[devshell]
packages = [
    "alejandra",
    "dprint",
]

[[commands]]
package = "treefmt"
category = "formatter"

[[commands]]
package = "toolchain"
name = "cargo"
help = "manage dependencies and the full build cycle of rust programs"
category = "devtools"

[[commands]]
package = "toolchain"
name = "rustc"
help = "the rust compiler"
category = "devtools"
